/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'confirm', file:'confirm.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'gameOver', file:'gameOver.png'},
                          {name:'titleImg', file:'img2title.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'quesBox', file:'quesBox.png'},
                          {name:'confirm', file:'confirm.png'},
                          {name:'thinkImg', file:'img_think.png'},
                          {name:'imgFront', file:'image1.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
