/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ques0', file:'ques0.png'},
                          {name:'ques1', file:'ques1.png'},
                          {name:'ques2', file:'ques2.png'},
                          {name:'ques3', file:'ques3.png'},
                          {name:'ques4', file:'ques4.png'},
                          {name:'ques5', file:'ques5.png'},
                          {name:'ques6', file:'ques6.png'},
                          {name:'ques7', file:'ques7.png'},
                          {name:'ques8', file:'ques8.png'},
                          {name:'ques9', file:'ques9.png'},
                          {name:'defIntersectLines', file:'defIntersectLines.png'},
                          {name:'imgIntersectLines', file:'imgIntersectLines.png'},
                          {name:'infoIntersectLines', file:'infoIntersectLines.png'},
                          {name:'defParallelLines', file:'defParallelLines.png'},
                          {name:'imgParallelLines', file:'imgParallelLines.png'},
                          {name:'infoParallelLines', file:'infoParallelLines.png'},
                          {name:'imgYes', file:'imgYes.png'},
                          {name:'defParallelYes', file:'defParallelYes.png'},
                          {name:'imgNo', file:'imgNo.png'},
                          {name:'defParallelNo', file:'defParallelNo.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'topText', file:'topText.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
