/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'apple', file:'apple.png'},
                          {name:'bag', file:'bag.png'},
                          {name:'balloon', file:'balloon.png'},
                          {name:'book', file:'book.png'},
                          {name:'bread', file:'bread.png'},
                          {name:'cake', file:'cake.png'},
                          {name:'cap', file:'cap.png'},
                          {name:'doll', file:'doll.png'},
                          {name:'food', file:'food.png'},
                          {name:'grapes', file:'grapes.png'},
                          {name:'ice', file:'ice.png'},
                          {name:'lays', file:'lays.png'},
                          {name:'mango', file:'mango.png'},
                          {name:'orange', file:'orange.png'},
                          {name:'papaya', file:'papaya.png'},
                          {name:'pear', file:'pear.png'},
                          {name:'pen', file:'pen.png'},
                          {name:'pomogranate', file:'pomogranate.png'},
                          {name:'roti', file:'roti.png'},
                          {name:'rs5', file:'rs5.jpg'},
                          {name:'rs10', file:'rs10.jpg'},
                          {name:'rs25', file:'rs25.jpg'},
                          {name:'rs50', file:'rs50.jpg'},
                          {name:'rs100', file:'rs100.jpg'},
                          {name:'moneyNeeded', file:'moneyNeeded.png'},
                          {name:'moneyOk', file:'moneyOk.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
