/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'snake', file:'snake.png'},
                          {name:'rhino', file:'rhino.png'},
                          {name:'elephant', file:'elephant.png'},
                          {name:'bear', file:'bear.png'},
                          {name:'monkey', file:'monkey.png'},
                          {name:'turtle', file:'turtle.png'},
                          {name:'jackal', file:'jackal.png'},
                          {name:'tiger', file:'tiger.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'snake', file:'snake.ogg'},
                          {name:'rhino', file:'rhino.ogg'},
                          {name:'elephant', file:'elephant.ogg'},
                          {name:'bear', file:'bear.ogg'},
                          {name:'monkey', file:'monkey.ogg'},
                          {name:'turtle', file:'turtle.ogg'},
                          {name:'jackal', file:'jackal.ogg'},
                          {name:'tiger', file:'tiger.ogg'}]});
}
