/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'comma.png', file:'comma.png'},
                          {name:'dot.png', file:'dot.png'},
                          {name:'backImage.png', file:'backImage.png'},
                          {name:'wild', file:'wild.png'},
                          {name:'transportation', file:'transportation.png'},
                          {name:'objects', file:'objects.png'},
                          {name:'tiger', file:'tiger.png'},
                          {name:'elephant', file:'elephant.png'},
                          {name:'jackal', file:'jackal.png'},
                          {name:'bear', file:'bear.png'},
                          {name:'rhino', file:'rhino.png'},
                          {name:'monkey', file:'monkey.png'},
                          {name:'turtle', file:'turtle.png'},
                          {name:'snake', file:'snake.png'},
                          {name:'aeroplane', file:'aeroplane.png'},
                          {name:'ship', file:'ship.png'},
                          {name:'cart', file:'cart.png'},
                          {name:'bus', file:'bus.png'},
                          {name:'cycle', file:'cycle.png'},
                          {name:'boat', file:'boat.png'},
                          {name:'tempo', file:'tempo.png'},
                          {name:'truck', file:'truck.png'},
                          {name:'desk', file:'desk.png'},
                          {name:'bench', file:'bench.png'},
                          {name:'brush', file:'brush.png'},
                          {name:'soap', file:'soap.png'},
                          {name:'kite', file:'kite.png'},
                          {name:'bag', file:'bag.png'},
                          {name:'book', file:'book.png'},
                          {name:'ladder', file:'ladder.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
