/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'bag', file:'bag.png'},
                          {name:'bench', file:'bench.png'},
                          {name:'book', file:'book.png'},
                          {name:'brush', file:'brush.png'},
                          {name:'desk', file:'desk.png'},
                          {name:'kite', file:'kite.png'},
                          {name:'ladder', file:'ladder.png'},
                          {name:'soap', file:'soap.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'bag', file:'bag.ogg'},
                          {name:'bench', file:'bench.ogg'},
                          {name:'book', file:'book.ogg'},
                          {name:'brush', file:'brush.ogg'},
                          {name:'desk', file:'desk.ogg'},
                          {name:'kite', file:'kite.ogg'},
                          {name:'ladder', file:'ladder.ogg'},
                          {name:'soap', file:'soap.ogg'}]});
}
