/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'crow', file:'crow.png'},
                          {name:'parrot', file:'parrot.png'},
                          {name:'eagle', file:'eagle.png'},
                          {name:'pigeon', file:'pigeon.png'},
                          {name:'mynah', file:'mynah.png'},
                          {name:'owl', file:'owl.png'},
                          {name:'egret', file:'egret.png'},
                          {name:'sparrow', file:'sparrow.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'crow', file:'crow.ogg'},
                          {name:'parrot', file:'parrot.ogg'},
                          {name:'eagle', file:'eagle.ogg'},
                          {name:'pigeon', file:'pigeon.ogg'},
                          {name:'mynah', file:'mynah.ogg'},
                          {name:'owl', file:'owl.ogg'},
                          {name:'egret', file:'egret.ogg'},
                          {name:'sparrow', file:'sparrow.ogg'}]});
}
