/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'a', file:'a.png'},
                          {name:'b', file:'b.png'},
                          {name:'c', file:'c.png'},
                          {name:'d', file:'d.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'wrong.png'},
                          {name:'answer1', file:'ques1def.png'},
                          {name:'answer2', file:'ques2def.png'},
                          {name:'answer3', file:'ques3def.png'},
                          {name:'answer4', file:'ques4def.png'},
                          {name:'answer5', file:'ques5def.png'},
                          {name:'answer6', file:'ques6def.png'},
                          {name:'answer7', file:'ques7def.png'},
                          {name:'answer8', file:'ques8def.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
