/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'doctor', file:'doctor.png'},
                          {name:'farmer', file:'farmer.png'},
                          {name:'pilot', file:'pilot.png'},
                          {name:'player', file:'player.png'},
                          {name:'policeman', file:'policeman.png'},
                          {name:'soldier', file:'soldier.png'},
                          {name:'tailor', file:'tailor.png'},
                          {name:'teacher', file:'teacher.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'doctor', file:'doctor.ogg'},
                          {name:'farmer', file:'farmer.ogg'},
                          {name:'pilot', file:'pilot.ogg'},
                          {name:'player', file:'player.ogg'},
                          {name:'policeman', file:'policeman.ogg'},
                          {name:'soldier', file:'soldier.ogg'},
                          {name:'tailor', file:'tailor.ogg'},
                          {name:'teacher', file:'teacher.ogg'}]});
}
