/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'circle1', file:'circle1.png'},
                          {name:'circle2', file:'circle2.png'},
                          {name:'circle3', file:'circle3.png'},
                          {name:'circle4', file:'circle4.png'},
                          {name:'quad1', file:'quad1.png'},
                          {name:'quad2', file:'quad2.png'},
                          {name:'quad3', file:'quad3.png'},
                          {name:'quad4', file:'quad4.png'},
                          {name:'dropHere', file:'dropHere.png'},
                          {name:'circle21', file:'circle21.png'},
                          {name:'circle22', file:'circle22.png'},
                          {name:'circle23', file:'circle23.png'},
                          {name:'circle24', file:'circle24.png'},
                          {name:'quad21', file:'quad21.png'},
                          {name:'quad22', file:'quad22.png'},
                          {name:'quad23', file:'quad23.png'},
                          {name:'quad24', file:'quad24.png'},
                          {name:'triangle21', file:'triangle21.png'},
                          {name:'triangle22', file:'triangle22.png'},
                          {name:'triangle23', file:'triangle23.png'},
                          {name:'triangle24', file:'triangle24.png'},
                          {name:'main', file:'main.png'},
                          {name:'circle31', file:'circle31.png'},
                          {name:'circle32', file:'circle32.png'},
                          {name:'quad31', file:'quad31.png'},
                          {name:'quad32', file:'quad32.png'},
                          {name:'quad33', file:'quad33.png'},
                          {name:'quad34', file:'quad34.png'},
                          {name:'triangle31', file:'triangle31.png'},
                          {name:'triangle32', file:'triangle32.png'},
                          {name:'triangle33', file:'triangle33.png'},
                          {name:'triangle34', file:'triangle34.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
