/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'optionBorder.png', file:'optionBorder.png'},
                          {name:'optionBorderHover.png', file:'optionBorderHover.png'},
                          {name:'listenAgain.png', file:'listenAgain.png'},
                          {name:'black', file:'black.png'},
                          {name:'blue', file:'blue.png'},
                          {name:'brown', file:'brown.png'},
                          {name:'green', file:'green.png'},
                          {name:'purple', file:'purple.png'},
                          {name:'orange', file:'orange.png'},
                          {name:'red', file:'red.png'},
                          {name:'yellow', file:'yellow.png'},
                          {name:'white', file:'white.png'},
                          {name:'background.jpg', file:'background.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'byebye', file:'../../karma/audio/byebye.ogg'},
                          {name:'black', file:'black.ogg'},
                          {name:'blue', file:'blue.ogg'},
                          {name:'brown', file:'brown.ogg'},
                          {name:'green', file:'green.ogg'},
                          {name:'purple', file:'purple.ogg'},
                          {name:'orange', file:'orange.ogg'},
                          {name:'red', file:'red.ogg'},
                          {name:'yellow', file:'yellow.ogg'},
                          {name:'white', file:'white.ogg'}]});
}
