/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'bgAns', file:'bgAns.png'},
                          {name:'bgMessage', file:'bgMessage.png'},
                          {name:'bgQuestion', file:'bgQuestion.png'},
                          {name:'bgQues', file:'bgQues.png'},
                          {name:'gameOver', file:'gameOver.png'},
                          {name:'check.png', file:'check.png'},
                          {name:'img0', file:'img0.png'},
                          {name:'img0Clicked', file:'img0Clicked.png'},
                          {name:'img1', file:'img1.png'},
                          {name:'img1Clicked', file:'img1Clicked.png'},
                          {name:'img2', file:'img2.png'},
                          {name:'img2Clicked', file:'img2Clicked.png'},
                          {name:'img3', file:'img3.png'},
                          {name:'img3Clicked', file:'img3Clicked.png'},
                          {name:'img4', file:'img4.png'},
                          {name:'img4Clicked', file:'img4Clicked.png'},
                          {name:'img5', file:'img5.png'},
                          {name:'img5Clicked', file:'img5Clicked.png'},
                          {name:'img6', file:'img6.png'},
                          {name:'img6Clicked', file:'img6Clicked.png'},
                          {name:'img7', file:'img7.png'},
                          {name:'img7Clicked', file:'img7Clicked.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
