/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'bulbul', file:'bulbul.jpg'},
                          {name:'crane', file:'crane.jpg'},
                          {name:'egret', file:'egret.jpg'},
                          {name:'kingfisher', file:'kingfisher.jpg'},
                          {name:'ostrich', file:'ostrich.jpg'},
                          {name:'penguin', file:'penguin.jpg'},
                          {name:'swan', file:'swan.jpg'},
                          {name:'swift', file:'swift.jpg'},
                          {name:'vulture', file:'vulture.jpg'},
                          {name:'woodpecker', file:'woodpecker.jpg'},
                          {name:'volImage.png', file:'volImage.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'bulbul', file:'bulbul.ogg'},
                          {name:'crane', file:'crane.ogg'},
                          {name:'egret', file:'egret.ogg'},
                          {name:'kingfisher', file:'kingfisher.ogg'},
                          {name:'ostrich', file:'ostrich.ogg'},
                          {name:'penguin', file:'penguin.ogg'},
                          {name:'swan', file:'swan.ogg'},
                          {name:'swift', file:'swift.ogg'},
                          {name:'vulture', file:'vulture.ogg'},
                          {name:'woodpecker', file:'woodpecker.ogg'}]});
}
