/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'a', file:'a.png'},
                          {name:'b', file:'b.png'},
                          {name:'c', file:'c.png'},
                          {name:'d', file:'d.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'wrong.png'},
                          {name:'line_segment', file:'line_segment.png'},
                          {name:'scale', file:'scale.png'},
                          {name:'lines', file:'lines.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
