/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ball', file:'ball.png'},
                          {name:'banana', file:'banana.png'},
                          {name:'cup', file:'cup.png'},
                          {name:'flower', file:'flower.png'},
                          {name:'glass', file:'glass.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
