/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'January', file:'January.png'},
                          {name:'small_January', file:'small_January.png'},
                          {name:'February', file:'February.png'},
                          {name:'small_February', file:'small_February.png'},
                          {name:'March', file:'March.png'},
                          {name:'small_March', file:'small_March.png'},
                          {name:'April', file:'April.png'},
                          {name:'small_April', file:'small_April.png'},
                          {name:'May', file:'May.png'},
                          {name:'small_May', file:'small_May.png'},
                          {name:'June', file:'June.png'},
                          {name:'small_June', file:'small_June.png'},
                          {name:'July', file:'July.png'},
                          {name:'small_July', file:'small_July.png'},
                          {name:'August', file:'August.png'},
                          {name:'small_August', file:'small_August.png'},
                          {name:'September', file:'September.png'},
                          {name:'small_September', file:'small_September.png'},
                          {name:'October', file:'October.png'},
                          {name:'small_October', file:'small_October.png'},
                          {name:'November', file:'November.png'},
                          {name:'small_November', file:'small_November.png'},
                          {name:'December', file:'December.png'},
                          {name:'small_December', file:'small_December.png'},
                          {name:'check', file:'check.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'January', file:'January.ogg'},
                          {name:'February', file:'February.ogg'},
                          {name:'March', file:'March.ogg'},
                          {name:'April', file:'April.ogg'},
                          {name:'May', file:'May.ogg'},
                          {name:'June', file:'June.ogg'},
                          {name:'July', file:'July.ogg'},
                          {name:'August', file:'August.ogg'},
                          {name:'September', file:'September.ogg'},
                          {name:'October', file:'October.ogg'},
                          {name:'November', file:'November.ogg'},
                          {name:'December', file:'December.ogg'}]});
}
