/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'cap', file:'cap.png'},
                          {name:'shirt', file:'shirt.png'},
                          {name:'coat', file:'coat.png'},
                          {name:'dress', file:'dress.png'},
                          {name:'skirt', file:'skirt.png'},
                          {name:'gloves', file:'gloves.png'},
                          {name:'socks', file:'socks.png'},
                          {name:'shoes', file:'shoes.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'cap', file:'cap.ogg'},
                          {name:'shirt', file:'shirt.ogg'},
                          {name:'coat', file:'coat.ogg'},
                          {name:'dress', file:'dress.ogg'},
                          {name:'skirt', file:'skirt.ogg'},
                          {name:'gloves', file:'gloves.ogg'},
                          {name:'socks', file:'socks.ogg'},
                          {name:'shoes', file:'shoes.ogg'}]});
}
