/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ques0', file:'ques0.png'},
                          {name:'img0', file:'img0.png'},
                          {name:'ques1', file:'ques1.png'},
                          {name:'img1', file:'img1.png'},
                          {name:'ques2', file:'ques2.png'},
                          {name:'img2', file:'img2.png'},
                          {name:'ques3', file:'ques3.png'},
                          {name:'img3', file:'img3.png'},
                          {name:'ques4', file:'ques4.png'},
                          {name:'img4', file:'img4.png'},
                          {name:'ques5', file:'ques5.png'},
                          {name:'img5', file:'img5.png'},
                          {name:'gameOver.png', file:'gameOver.png'},
                          {name:'bgLeft.png', file:'bgLeft.png'},
                          {name:'check.png', file:'check.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
