/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ear', file:'ear.png'},
                          {name:'hair', file:'hair.png'},
                          {name:'nose', file:'nose.png'},
                          {name:'arm', file:'arm.png'},
                          {name:'hand', file:'hand.png'},
                          {name:'finger', file:'finger.png'},
                          {name:'knee', file:'knee.png'},
                          {name:'foot', file:'foot.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'ear', file:'ear.ogg'},
                          {name:'hair', file:'hair.ogg'},
                          {name:'nose', file:'nose.ogg'},
                          {name:'arm', file:'arm.ogg'},
                          {name:'hand', file:'hand.ogg'},
                          {name:'finger', file:'finger.ogg'},
                          {name:'knee', file:'knee.ogg'},
                          {name:'foot', file:'foot.ogg'}]});
}
