/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'background.jpg', file:'background.jpg'},
                          {name:'fishLeft', file:'fishLeft.png'},
                          {name:'fishRight', file:'fishRight.png'},
                          {name:'gameover', file:'gameover.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'},
                          {name:'byebye', file:'byebye.ogg'},
                          {name:'complain', file:'chhyaa.ogg'},
                          {name:'eat', file:'GohiEat.ogg'},
                          {name:'instruction', file:'GohilaiMachaInstruction.ogg'}]});
}
