/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ship', file:'ship.png'},
                          {name:'airplane', file:'airplane.png'},
                          {name:'boat', file:'boat.png'},
                          {name:'bus', file:'bus.png'},
                          {name:'tempo', file:'tempo.png'},
                          {name:'truck', file:'truck.png'},
                          {name:'bicycle', file:'bicycle.png'},
                          {name:'cart', file:'cart.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'ship', file:'ship.ogg'},
                          {name:'airplane', file:'airplane.ogg'},
                          {name:'boat', file:'boat.ogg'},
                          {name:'bus', file:'bus.ogg'},
                          {name:'tempo', file:'tempo.ogg'},
                          {name:'truck', file:'truck.ogg'},
                          {name:'bicycle', file:'bicycle.ogg'},
                          {name:'cart', file:'cart.ogg'}]});
}
