/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'cheetah', file:'cheetah.jpg'},
                          {name:'crocodile', file:'crocodile.jpg'},
                          {name:'dinosaur', file:'dinosaur.jpg'},
                          {name:'giraffe', file:'giraffe.jpg'},
                          {name:'kangaroo', file:'kangaroo.jpg'},
                          {name:'octopus', file:'octopus.jpg'},
                          {name:'panda', file:'panda.jpg'},
                          {name:'rhinoceros', file:'rhinoceros.jpg'},
                          {name:'whale', file:'whale.jpg'},
                          {name:'zebra', file:'zebra.jpg'},
                          {name:'volImage.png', file:'volImage.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'cheetah', file:'cheetah.ogg'},
                          {name:'crocodile', file:'crocodile.ogg'},
                          {name:'dinosaur', file:'dinosaur.ogg'},
                          {name:'giraffe', file:'giraffe.ogg'},
                          {name:'kangaroo', file:'kangaroo.ogg'},
                          {name:'octopus', file:'octopus.ogg'},
                          {name:'panda', file:'panda.ogg'},
                          {name:'rhinoceros', file:'rhinoceros.ogg'},
                          {name:'whale', file:'whale.ogg'},
                          {name:'zebra', file:'zebra.ogg'}]});
}
