/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'rice', file:'rice.png'},
                          {name:'daal', file:'daal.png'},
                          {name:'sweet', file:'sweet.png'},
                          {name:'jelly', file:'jelly.png'},
                          {name:'bread', file:'bread.png'},
                          {name:'bun', file:'bun.png'},
                          {name:'cake', file:'cake.png'},
                          {name:'ice-cream', file:'ice-cream.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'rice', file:'rice.ogg'},
                          {name:'daal', file:'daal.ogg'},
                          {name:'sweet', file:'sweet.ogg'},
                          {name:'jelly', file:'jelly.ogg'},
                          {name:'bread', file:'bread.ogg'},
                          {name:'bun', file:'bun.ogg'},
                          {name:'cake', file:'cake.ogg'},
                          {name:'ice-cream', file:'ice-cream.ogg'}]});
}
