/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'background', file:'background.jpg'},
                          {name:'blueTruck0', file:'blueTruck0.png'},
                          {name:'boxes', file:'boxes.png'},
                          {name:'bridgeUp', file:'bridgeUp.png'},
                          {name:'chooseLevel', file:'chooseLevel.png'},
                          {name:'correctFace', file:'correctFace.png'},
                          {name:'help', file:'help.png'},
                          {name:'imgComputerTruck', file:'imgComputerTruck.png'},
                          {name:'imgTop', file:'imgTop.png'},
                          {name:'imgYourTruck', file:'imgYourTruck.png'},
                          {name:'incorrectFace', file:'incorrectFace.png'},
                          {name:'info', file:'info.png'},
                          {name:'infoText', file:'infoText.png'},
                          {name:'level1', file:'level1.png'},
                          {name:'level2', file:'level2.png'},
                          {name:'level3', file:'level3.png'},
                          {name:'levelArrow', file:'levelArrow.png'},
                          {name:'main_bridge', file:'main_bridge.png'},
                          {name:'multiplySecImg', file:'multiplySecImg.png'},
                          {name:'redTruck0', file:'redTruck0.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
