/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'computer_body', file:'computer_body.png'},
                          {name:'computer_base', file:'computer_base.png'},
                          {name:'computer_top', file:'computer_top.png'},
                          {name:'player_top', file:'player_top.png'},
                          {name:'player_body', file:'player_body.png'},
                          {name:'player_base', file:'player_base.png'},
                          {name:'bgContainer', file:'bgContainer.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
