/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'hang0', file:'hang0.png'},
                          {name:'hang1', file:'hang1.png'},
                          {name:'hang2', file:'hang2.png'},
                          {name:'hang3', file:'hang3.png'},
                          {name:'mainImage', file:'hang_man_image.png'},
                          {name:'kitchen', file:'one_or_more_kitchen_utensils.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
