/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'he', file:'he.png'},
                          {name:'drinking', file:'he_drinking.png'},
                          {name:'playing', file:'he_playing.png'},
                          {name:'running', file:'he_running.png'},
                          {name:'walking', file:'he_walking.png'},
                          {name:'she', file:'she.png'},
                          {name:'reading', file:'she_reading.png'},
                          {name:'washing', file:'she_washing.png'},
                          {name:'jumping', file:'she_jumping.png'},
                          {name:'sitting', file:'she_sitting.png'},
                          {name:'it', file:'it.png'},
                          {name:'climbing', file:'it_climbing.png'},
                          {name:'eating', file:'it_eating.png'},
                          {name:'carrying', file:'it_carrying.png'},
                          {name:'laughing', file:'it_laughing.png'},
                          {name:'exclamation_point', file:'exclamation_point.png'},
                          {name:'question_mark', file:'question_mark.png'},
                          {name:'question_mark2', file:'question_mark2.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
