/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'banana', file:'banana.png'},
                          {name:'peach', file:'peach.png'},
                          {name:'mango', file:'mango.png'},
                          {name:'apple', file:'apple.png'},
                          {name:'papaya', file:'papaya.png'},
                          {name:'pear', file:'pear.png'},
                          {name:'orange', file:'orange.png'},
                          {name:'grapes', file:'grapes.png'},
                          {name:'vocabImg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'banana', file:'banana.ogg'},
                          {name:'peach', file:'peach.ogg'},
                          {name:'mango', file:'mango.ogg'},
                          {name:'apple', file:'apple.ogg'},
                          {name:'papaya', file:'papaya.ogg'},
                          {name:'pear', file:'pear.ogg'},
                          {name:'orange', file:'orange.ogg'},
                          {name:'grapes', file:'grapes.ogg'}]});
}
