/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'cow', file:'cow.png'},
                          {name:'goat', file:'goat.png'},
                          {name:'sheep', file:'sheep.png'},
                          {name:'pig', file:'pig.png'},
                          {name:'cock', file:'cock.png'},
                          {name:'horse', file:'horse.png'},
                          {name:'duck', file:'duck.png'},
                          {name:'rabbit', file:'rabbit.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'cow', file:'cow.ogg'},
                          {name:'goat', file:'goat.ogg'},
                          {name:'sheep', file:'sheep.ogg'},
                          {name:'pig', file:'pig.ogg'},
                          {name:'cock', file:'cock.ogg'},
                          {name:'horse', file:'horse.ogg'},
                          {name:'duck', file:'duck.ogg'},
                          {name:'rabbit', file:'rabbit.ogg'}]});
}
