/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'plussign', file:'plussign.png'},
                          {name:'scorebox', file:'scorebox.png'},
                          {name:'ball', file:'ball37px.png'},
                          {name:'balloon', file:'balloon37px.png'},
                          {name:'banana', file:'banana37px.png'},
                          {name:'chilli', file:'chilli.png'},
                          {name:'fish', file:'fish64px.png'},
                          {name:'flower', file:'flower37px.png'},
                          {name:'normal_chimp', file:'normalChimp_120x125.png'},
                          {name:'happy_chimp', file:'happyChimp_120x125.png'},
                          {name:'sad_chimp', file:'sadChimp_120x125.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'},
                          {name:'trigger', file:'trigger.ogg'}]});
}
