/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'Acute-Angle', file:'Acute-Angle.png'},
                          {name:'Circle', file:'Circle.png'},
                          {name:'Decagon', file:'Decagon.png'},
                          {name:'Hexagon', file:'Hexagon.png'},
                          {name:'Nonagon', file:'Nonagon.png'},
                          {name:'Rectangle', file:'Rectangle.png'},
                          {name:'Octagon', file:'Octagon.png'},
                          {name:'Parallelogram', file:'Parallelogram.png'},
                          {name:'Pentagon', file:'Pentagon.png'},
                          {name:'Rhombus', file:'Rhombus.png'},
                          {name:'Right-Angle', file:'Right-Angle.png'},
                          {name:'Heptagon', file:'Heptagon.png'},
                          {name:'Square', file:'Square.png'},
                          {name:'Triangle', file:'Triangle.png'},
                          {name:'Obtuse-Angle', file:'Obtuse-Angle.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
