/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'section1.png', file:'section1.png'},
                          {name:'line0', file:'line0.png'},
                          {name:'line30', file:'line30.png'},
                          {name:'line45', file:'line45.png'},
                          {name:'line60', file:'line60.png'},
                          {name:'line90', file:'line90.png'},
                          {name:'line120', file:'line120.png'},
                          {name:'line135', file:'line135.png'},
                          {name:'line150', file:'line150.png'},
                          {name:'line180', file:'line180.png'},
                          {name:'protractor.png', file:'protractor.png'},
                          {name:'section2ImgHint', file:'section2ImgHint.png'},
                          {name:'angle', file:'angle.png'},
                          {name:'gameOverSuccess', file:'gameOverSuccess.png'},
                          {name:'gameOverTry', file:'gameOverTry.png'},
                          {name:'medal.png', file:'medal.png'},
                          {name:'section3ImgTop', file:'section3ImgTop.png'},
                          {name:'section3.png', file:'section3.png'},
                          {name:'ball.png', file:'ball.png'},
                          {name:'boom', file:'boom.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'},
                          {name:'explode', file:'explode.ogg'}]});
}
