/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'dot', file:'dot.png'},
                          {name:'a', file:'a.png'},
                          {name:'b', file:'b.png'},
                          {name:'c', file:'c.png'},
                          {name:'d', file:'d.png'},
                          {name:'check', file:'check.png'},
                          {name:'gameOverSuccess', file:'gameOverSuccess.png'},
                          {name:'gameOverTry', file:'gameOverTry.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'wrong', file:'wrong.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
