/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'Apple', file:'Apple.png'},
                          {name:'Bag', file:'Bag.png'},
                          {name:'Banana', file:'Banana.png'},
                          {name:'Cake', file:'Cake.png'},
                          {name:'Coat', file:'Coat.png'},
                          {name:'Cow', file:'Cow.png'},
                          {name:'Elephant', file:'Elephant.png'},
                          {name:'Flower', file:'Flower.png'},
                          {name:'Grapes', file:'Grapes.png'},
                          {name:'Monkey', file:'Monkey.png'},
                          {name:'Pigeon', file:'Pigeon.png'},
                          {name:'Rat', file:'Rat.png'},
                          {name:'Tomato', file:'Tomato.png'},
                          {name:'Tree', file:'Tree.png'},
                          {name:'Boat', file:'Boat.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
