/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'ele0', file:'ele0.png'},
                          {name:'house0', file:'house0.png'},
                          {name:'ship0', file:'ship0.png'},
                          {name:'ele1', file:'ele1.png'},
                          {name:'house1', file:'house1.png'},
                          {name:'ship1', file:'ship1.png'},
                          {name:'ele2', file:'ele2.png'},
                          {name:'house2', file:'house2.png'},
                          {name:'ship2', file:'ship2.png'},
                          {name:'ele3', file:'ele3.png'},
                          {name:'house3', file:'house3.png'},
                          {name:'ship3', file:'ship3.png'},
                          {name:'ele4', file:'ele4.png'},
                          {name:'house4', file:'house4.png'},
                          {name:'ship4', file:'ship4.png'},
                          {name:'ele5', file:'ele5.png'},
                          {name:'house5', file:'house5.png'},
                          {name:'ship5', file:'ship5.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'background.jpg', file:'background.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'}]});
}
