/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'img0', file:'img0.png'},
                          {name:'img0More', file:'img0More.png'},
                          {name:'img1', file:'img1.png'},
                          {name:'img1More', file:'img1More.png'},
                          {name:'img2', file:'img2.png'},
                          {name:'img2More', file:'img2More.png'},
                          {name:'img3', file:'img3.png'},
                          {name:'img3More', file:'img3More.png'},
                          {name:'img4', file:'img4.png'},
                          {name:'img4More', file:'img4More.png'},
                          {name:'img5', file:'img5.png'},
                          {name:'img5More', file:'img5More.png'},
                          {name:'img6', file:'img6.png'},
                          {name:'img6More', file:'img6More.png'},
                          {name:'img7', file:'img7.png'},
                          {name:'img7More', file:'img7More.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
