/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'leaf', file:'leaf.png'},
                          {name:'branch', file:'branch.png'},
                          {name:'fruit', file:'fruit.png'},
                          {name:'tree', file:'tree.png'},
                          {name:'bush', file:'bush.png'},
                          {name:'flower', file:'flower.png'},
                          {name:'grass', file:'grass.png'},
                          {name:'plant', file:'plant.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'leaf', file:'leaf.ogg'},
                          {name:'branch', file:'branch.ogg'},
                          {name:'fruit', file:'fruit.ogg'},
                          {name:'tree', file:'tree.ogg'},
                          {name:'bush', file:'bush.ogg'},
                          {name:'flower', file:'flower.ogg'},
                          {name:'grass', file:'grass.ogg'},
                          {name:'plant', file:'plant.ogg'}]});
}
