/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'1', file:'Rs1.png'},
                          {name:'2', file:'Rs2.png'},
                          {name:'5', file:'Rs5.png'},
                          {name:'10', file:'Rs10.png'},
                          {name:'20', file:'Rs20.png'},
                          {name:'25', file:'Rs25.png'},
                          {name:'50', file:'Rs50.png'},
                          {name:'100', file:'Rs100.png'},
                          {name:'500', file:'Rs500.png'},
                          {name:'1000', file:'Rs1000.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'optionBorder.png', file:'optionBorder.png'},
                          {name:'optionBorderHover.png', file:'optionBorderHover.png'},
                          {name:'listenAgain.png', file:'listenAgain.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'},
                          {name:'1', file:'Rs1.ogg'},
                          {name:'2', file:'Rs2.ogg'},
                          {name:'5', file:'Rs5.ogg'},
                          {name:'10', file:'Rs10.ogg'},
                          {name:'20', file:'Rs20.ogg'},
                          {name:'25', file:'Rs25.ogg'},
                          {name:'50', file:'Rs50.ogg'},
                          {name:'100', file:'Rs100.ogg'},
                          {name:'500', file:'Rs500.ogg'},
                          {name:'1000', file:'Rs1000.ogg'},
                          {name:'byebye', file:'byebye.ogg'}]});
}
