/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'house', file:'house.png'},
                          {name:'roof', file:'roof.png'},
                          {name:'floor', file:'floor.png'},
                          {name:'window', file:'window.png'},
                          {name:'door', file:'door.png'},
                          {name:'road', file:'road.png'},
                          {name:'garden', file:'garden.png'},
                          {name:'wall', file:'wall.png'},
                          {name:'vocabImg.jpg', file:'vocabImg.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'trigger', file:'../../karma/audio/trigger.ogg'},
                          {name:'house', file:'house.ogg'},
                          {name:'roof', file:'roof.ogg'},
                          {name:'floor', file:'floor.ogg'},
                          {name:'window', file:'window.ogg'},
                          {name:'door', file:'door.ogg'},
                          {name:'road', file:'road.ogg'},
                          {name:'garden', file:'garden.ogg'},
                          {name:'wall', file:'wall.ogg'}]});
}
