/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'background.jpg', file:'background.jpg'},
                          {name:'rubbish', file:'rubbish.png'},
                          {name:'rubbish_open', file:'rubbish_open.png'},
                          {name:'shadow', file:'shadow.png'},
                          {name:'sheep1', file:'sheep1.png'},
                          {name:'sheep2', file:'sheep2.png'},
                          {name:'sheep3', file:'sheep3.png'},
                          {name:'title', file:'title.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
