/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'dragHere', file:'dragHere.png'},
                          {name:'dropHere', file:'dropHere.png'},
                          {name:'dropHere1', file:'dropHere1.png'},
                          {name:'fruit1', file:'fruit1.png'},
                          {name:'fruit2', file:'fruit2.png'},
                          {name:'fruit3', file:'fruit3.png'},
                          {name:'fruit4', file:'fruit4.png'},
                          {name:'veg1', file:'veg1.png'},
                          {name:'veg2', file:'veg2.png'},
                          {name:'veg3', file:'veg3.png'},
                          {name:'veg4', file:'veg4.png'},
                          {name:'other1', file:'other1.png'},
                          {name:'other2', file:'other2.png'},
                          {name:'other3', file:'other3.png'},
                          {name:'other4', file:'other4.png'},
                          {name:'help2', file:'help2.png'},
                          {name:'help3', file:'help3.png'}],
                  audio: [{name:'correct', file:'../../karma/audio/ne_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/ne_incorrect.ogg'}]});
}
