/*
 * This file was generated by build.py on 2012/11/28 12:26:03.
 * Do not edit.
 * cwd: F:\repo\EPaathi18n\src
 * command: build.py --stable --xo --setversion=248 --restrict=.*-en --lang=np
 */
function lesson_karma() {
    return Karma({image: [{name:'help', file:'help.png'},
                          {name:'correct', file:'correct.png'},
                          {name:'incorrect', file:'incorrect.png'},
                          {name:'optionBorder.png', file:'optionBorder.png'},
                          {name:'optionBorderHover.png', file:'optionBorderHover.png'},
                          {name:'listenAgain.png', file:'listenAgain.png'},
                          {name:'cat', file:'cat.png'},
                          {name:'cow', file:'cow.png'},
                          {name:'deer', file:'deer.png'},
                          {name:'dog', file:'dog.png'},
                          {name:'elephant', file:'elephant.png'},
                          {name:'horse', file:'horse.png'},
                          {name:'sheep', file:'sheep.png'},
                          {name:'background.jpg', file:'background.jpg'}],
                  audio: [{name:'correct', file:'../../karma/audio/en_correct.ogg'},
                          {name:'incorrect', file:'../../karma/audio/en_incorrect.ogg'},
                          {name:'byebye', file:'../../karma/audio/byebye.ogg'},
                          {name:'cat', file:'cat.ogg'},
                          {name:'cow', file:'cow.ogg'},
                          {name:'deer', file:'deer.ogg'},
                          {name:'dog', file:'dog.ogg'},
                          {name:'elephant', file:'elephant.ogg'},
                          {name:'horse', file:'horse.ogg'},
                          {name:'sheep', file:'sheep.ogg'}]});
}
